### ISSUE TITLE
Buildroot setup on Raspberry Pi server

### ISSUE THREAD

**Issue by abaa3023** [cu-ecen-aeld/final-project-maheshchnt#1]
DOD:

 Creating custom Buildroot image for Raspberry Pi 3 with necessary support packages
 Flashing the image onto SD card and booting the Raspberry Pi
 Connecting the hardware using ssh client and running basic cross-compiled C program.

Blockers: Raspberry pi 3B hardware is yet to be acquired from E-store. Planning to collect it tomorrow-07 November

**Comment by maheshchnt** [comment]
Received the hardware. Working on buildroot.

Blockers: Buildroot compilation fails while running post image script with below error message. I am currently debugging the issue


Error:
====

t-maheshchnt/buildroot/output/staging
>>>   Executing post-image script board/raspberrypi3/post-image.sh
INFO: cmd: "mkdir -p "/home/mgudipati/COURSE/AESD/PROJECT/BUILDROOT/final-project-maheshchnt/buildroot/output/build/genimage.tmp"" (stderr):
INFO: cmd: "rm -rf "/home/mgudipati/COURSE/AESD/PROJECT/BUILDROOT/final-project-maheshchnt/buildroot/output/build/genimage.tmp"/*" (stderr):
INFO: cmd: "mkdir -p "/home/mgudipati/COURSE/AESD/PROJECT/BUILDROOT/final-project-maheshchnt/buildroot/output/build/genimage.tmp"" (stderr):
INFO: cmd: "cp -a "/tmp/tmp.fB24zg24xy" "/home/mgudipati/COURSE/AESD/PROJECT/BUILDROOT/final-project-maheshchnt/buildroot/output/build/genimage.tmp/root"" (stderr):
INFO: cmd: "find '/home/mgudipati/COURSE/AESD/PROJECT/BUILDROOT/final-project-maheshchnt/buildroot/output/build/genimage.tmp/root' -depth -type d -printf '%P\0' | xargs -0 -I {} touch -r '/tmp/tmp.fB24zg24xy/{}' '/home/mgudipati/COURSE/AESD/PROJECT/BUILDROOT/final-project-maheshchnt/buildroot/output/build/genimage.tmp/root/{}'" (stderr):
ERROR: file(rpi-firmware/bootcode.bin): stat(/home/mgudipati/COURSE/AESD/PROJECT/BUILDROOT/final-project-maheshchnt/buildroot/output/images/rpi-firmware/bootcode.bin) failed: No such file or directory
ERROR: vfat(boot.vfat): could not setup rpi-firmware/bootcode.bin
make[1]: *** [Makefile:817: target-post-image] Error 1
make: *** [Makefile:84: _all] Error 2
make: Leaving directory '/home/mgudipati/COURSE/AESD/PROJECT/BUILDROOT/final-project-maheshchnt/buildroot'

**Comment by maheshchnt** [comment]
Buildroot compiled successfully and could boot the hardware with the compiled image.
Able to establish ssh connection between Raspberry pi and host server and transfer the files back and forth.
Could successfully run cross compiled image on hardware.

config file used to build the buildroot image for raspberry pi 3 B+ can be seen at below link
https://github.com/cu-ecen-aeld/final-project-maheshchnt/blob/main/base_external/configs/aesd_rpi_defconfig


Screenshots:
========

ifconfig output:
![ifconfig](https://user-images.githubusercontent.com/47424239/202837468-3d1edafd-8b63-4b80-9bba-be5781c46ee7.JPG)

root directory:

![root_dir](https://user-images.githubusercontent.com/47424239/202837482-e9307ca1-c8d9-4e4f-ad0b-769519ade448.JPG)

file transferring through winscp:

![winscp](https://user-images.githubusercontent.com/47424239/202837494-1a067cff-daf3-4682-b6f4-8e5a942066cb.JPG)
