### ISSUE TITLE
Camera integration with Raspberry Pi

### ISSUE THREAD

**Issue by abaa3023** [cu-ecen-aeld/final-project-maheshchnt#4]
DOD:

1. Integrating the camera driver with buildroot- Planning to use the existing UVC driver package that is already available in the kernel. 

2. Verifying the camera driver with test application - capturing the pictures and manually verifying if the pictures are captured.

Blockers: No blockers

**Comment by maheshchnt** [comment]
Able to capture frames from camera and store it on flash.

Tested camera capture from buildroot using test program.

Snapshots:
=======

Camera capture program screenshot:

![camera_capture](https://user-images.githubusercontent.com/47424239/202837618-5f5774ab-04e9-4852-89a6-061ef4089c7a.JPG)

Captured frames screenshot:
![captured_frames](https://user-images.githubusercontent.com/47424239/202837626-11af83f1-b0c7-4089-b9d6-9a0af58a996e.JPG)

**Comment by maheshchnt** [comment]
Attached the camera capture test code zip files

[camera_capture_test_code_files.zip](https://github.com/cu-ecen-aeld/final-project-maheshchnt/files/10046255/camera_capture_test_code_files.zip)


https://github.com/cu-ecen-aeld/final-project-abaa3023/tree/master/test/cam_capture
